server:
  port: 8761
management:
  port: 8082
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: development
server:
  port: 8761
management:
  port: 8082
  security:
    enabled: false
eureka:
  instance:
    hostname: discovery-server-xapi.cfapps.io
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://discovery-server-xapi.cfapps.io/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0