server:
  port: 8761
management:
  port: 8082
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
---
spring:
  profiles: development
server:
  port: 8761
management:
  port: 8082
  security:
    enabled: false
eureka:
  instance:
    hostname: discovery-server-xapi.cfapps.io
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false