server:
  port: ${EUREKA_SERVER_PORT:8761}
management:
  port: 8082
  security:
    enabled: false
eureka:
  enviroment: local
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
---
spring:
  profiles: development
server:
  port: ${EUREKA_SERVER_PORT:8761}
management:
  port: 8082
  security:
    enabled: false
eureka:
  enviroment: development
  instance:
    hostname: discovery-server-xapi.cfapps.io
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false