server:
  port: 8084
management:
  port: 8090
  security:
    enabled: false
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
exchange:
  apiProtocol: "http"
  apiDomain: "api.fixer.io"
  apiPath: "/latest"
---
spring:
  profiles: development
server:
  port: 8084
management:
  port: 8090
  security:
    enabled: false
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server-xapi.cfapps.io/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
exchange:
  apiProtocol: "http"
  apiDomain: "api.fixer.io"
  apiPath: "/lates